# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

USER root

RUN echo "===> Prepare packages..."  && \
        yum makecache fast && \
        yum install -y python sudo yum-plugin-ovl bash cronie crontabs && \
        sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && \
        chmod 0644 /etc/crontab && \
        yum clean all; \
    \
    echo "===> Allow webadm..."  && \
        echo "webadm ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/webadm ; \
    \
    echo "===> Enabling systemd..."  && \
        (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
        rm -f /lib/systemd/system/multi-user.target.wants/*;      \
        rm -f /etc/systemd/system/*.wants/*;                      \
        rm -f /lib/systemd/system/local-fs.target.wants/*;        \
        rm -f /lib/systemd/system/sockets.target.wants/*udev*;    \
        rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
        rm -f /lib/systemd/system/basic.target.wants/*;           \
        rm -f /lib/systemd/system/anaconda.target.wants/*

# L'activation de systemd n'est pas compatible avec un autre utilisateur que root : 
# https://stackoverflow.com/questions/36545105/docker-couldnt-find-an-alternative-telinit-implementation-to-spawn
# Need to run with --privileged, Need to include volume /sys/fs/cgroup
#USER webadm

